# Generated by Django 4.2.1 on 2023-05-18 14:34

import uuid

import django.db.models.deletion
from django.db import migrations, models

import common.constants.enums


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("app_store_id", models.CharField(blank=True, max_length=16)),
                ("app_store_slug", models.CharField(blank=True, max_length=127)),
                (
                    "app_store_status",
                    models.CharField(
                        choices=[("ready", "Ready"), ("updating", "Updating")],
                        default=common.constants.enums.AppStatus["READY"],
                        max_length=32,
                    ),
                ),
                (
                    "app_store_last_scraped_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("google_play_id", models.CharField(blank=True, max_length=127)),
                (
                    "google_play_status",
                    models.CharField(
                        choices=[("ready", "Ready"), ("updating", "Updating")],
                        default=common.constants.enums.AppStatus["READY"],
                        max_length=32,
                    ),
                ),
                (
                    "google_play_last_scraped_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                ("username", models.CharField(max_length=255)),
                (
                    "stars",
                    models.IntegerField(
                        choices=[
                            (1, "One"),
                            (2, "Two"),
                            (3, "Three"),
                            (4, "Four"),
                            (5, "Five"),
                        ]
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        choices=[
                            ("app_store", "App Store"),
                            ("google_play", "Google Play"),
                        ]
                    ),
                ),
                ("source_id", models.CharField(max_length=255)),
                ("source_created_at", models.DateTimeField()),
                (
                    "sentiment_str",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("is_sentiment_analyzed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
