# Generated by Django 4.2.1 on 2023-05-18 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="searchhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.application",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                condition=models.Q(("app_store_id", ""), _negated=True),
                fields=("app_store_id",),
                name="unique_app_store_id_non_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                condition=models.Q(("app_store_slug", ""), _negated=True),
                fields=("app_store_slug",),
                name="unique_app_store_slug_non_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                condition=models.Q(("google_play_id", ""), _negated=True),
                fields=("google_play_id",),
                name="unique_google_play_id_non_blank",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["source_id"], name="review_source_id_index"),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("market", "source_id"), name="uc_review_source_source_id"
            ),
        ),
    ]
