# Generated by Django 4.2.1 on 2023-05-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0004_application_description"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="searchhistory",
            constraint=models.UniqueConstraint(
                fields=("user", "application", "created_at"),
                name="uc_search_history_user_app_created_at",
            ),
        ),
    ]
