FROM python:3.10-slim as builder

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y build-essential
RUN pip install --no-cache-dir torch
RUN pip wheel --no-cache-dir --no-deps --wheel-dir=/wheels -r requirements.txt

FROM python:3.10-slim

WORKDIR /app
RUN mkdir ./staticfiles

COPY --from=builder /wheels /wheels
COPY . .

RUN pip install --no-cache-dir /wheels/*

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
